name: Build and Deploy Sphinx Documentation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install Pandoc
        run: |
          sudo apt update
          sudo apt-get install pandoc

      - name: Install libgdal-dev
        run: |
          sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable
          sudo apt-get update
          sudo apt-get install gdal-bin libgdal-dev
          pip install GDAL==`gdal-config --version`

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[doc]

      - name: Build Sphinx documentation
        run: |
          cd docs
          make clean
          make html
          ghp-import -f -n -p _build/html

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/docs'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html
